name: example
description: Set of extensions to safely set value to stream controllers in flutter and rxDart
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  safe_stream_value:
    path: ../
  rxdart: ^0.27.4
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true