name: safe_stream_value
description: Set of extensions to safely set value to stream controllers in flutter and rxDart
version: 0.0.1
homepage: https://github.com/javaherisaber/safe_stream_value

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
